"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/layout/AppShell";
import { TopNav } from "@/components/layout/TopNav";
import { Icons } from "@/components/icons";
import { PersonaAvatar } from "@/components/persona/PersonaAvatar";
import { Waveform } from "@/components/ui/Waveform";
import { api } from "@/lib/apiClient";
import { useSimulationStore } from "@/stores/simulationStore";

const MOCK_LOG = [
  { agent: "Persona Generator", color: "#5EEAD4", message: "Anchored on 'elderly, post-discharge, medication confusion.' Set politeness high, attention variable." },
  { agent: "Scenario Builder", color: "#93B4FF", message: "Added latent red flag: chest tightness, revealed after symptom probe OR ~2 min latency." },
  { agent: "Rubric Agent", color: "#B5ACFD", message: "Boosted weights on red-flag detection & escalation (high risk scenario)." },
  { agent: "Persona Generator", color: "#5EEAD4", message: "Voice: female, ~70-75, calm pace 130 wpm, slight tremor on first syllables." },
];

export default function PreviewPage() {
  const router = useRouter();
  const { persona, scenario, rubric, mode, agentLog } = useSimulationStore();
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const audioUrlRef = useRef<string | null>(null);
  const [isPlayingVoice, setIsPlayingVoice] = useState(false);
  const [voiceError, setVoiceError] = useState("");

  const p = persona || {
    name: "Margaret Lewis", age: 72, role: "Post-discharge patient", mood: "worried",
    traits: ["polite", "hesitant", "apologetic"], goal: "Understand new medication instructions",
    hidden_red_flag: "Chest tightness — reveals only if asked about symptoms or after ~2 min",
    behavior: "Apologetic, asks to repeat, easily distracted",
    voice_style: "Elderly, calm, slightly anxious — light tremor",
    opening_line: "Hi, I'm sorry to bother you. I was discharged yesterday and I'm confused about which pills I should take tonight.",
    avatar_preset: "margaret",
  };
  const s = scenario || { title: "Post-surgery follow-up call", description: "Margaret was discharged 36 hours ago. She'll call confused about her medication, but her real concern (chest tightness) only surfaces if you ask the right questions.", your_role: "Care coordinator", duration: "~5 min", objective: "Verify ID, identify urgent concerns, escalate", success_condition: "Patient is safely escalated", difficulty: "Medium" };
  const r = rubric || { items: [
    { name: "Identity verification", weight: 10, is_hot: false },
    { name: "Empathy", weight: 18, is_hot: false },
    { name: "Question quality", weight: 14, is_hot: false },
    { name: "Red-flag detection", weight: 20, is_hot: true },
    { name: "Escalation handling", weight: 18, is_hot: true },
    { name: "Clarity of next steps", weight: 10, is_hot: false },
    { name: "Nonverbal engagement", weight: 10, is_hot: false },
  ]};
  const resolvedMode = mode || "video";
  const resolvedAgentLog = agentLog.length ? agentLog : MOCK_LOG;
  const openingLineDuration = Math.max(3, Math.round(p.opening_line.split(" ").length / 2.8));

  useEffect(() => {
    return () => {
      if (audioRef.current) {
        audioRef.current.pause();
      }
      if (audioUrlRef.current) {
        URL.revokeObjectURL(audioUrlRef.current);
      }
    };
  }, []);

  const handlePlayVoice = async () => {
    try {
      setVoiceError("");
      setIsPlayingVoice(true);
      if (audioRef.current) {
        audioRef.current.pause();
      }
      if (audioUrlRef.current) {
        URL.revokeObjectURL(audioUrlRef.current);
        audioUrlRef.current = null;
      }

      const blob = await api.synthesizeVoice({
        text: p.opening_line,
        persona_name: p.name,
        voice_style: p.voice_style,
      });
      const url = URL.createObjectURL(blob);
      audioUrlRef.current = url;
      const audio = new Audio(url);
      audioRef.current = audio;
      audio.onended = () => setIsPlayingVoice(false);
      audio.onerror = () => {
        setVoiceError("Voice playback failed.");
        setIsPlayingVoice(false);
      };
      await audio.play();
    } catch (error) {
      setVoiceError(error instanceof Error ? error.message : "Voice playback failed.");
      setIsPlayingVoice(false);
    }
  };

  return (
    <AppShell>
      <TopNav active="Simulations" compact />
      <div style={{ flex: 1, padding: "24px 28px", overflow: "hidden", display: "flex", flexDirection: "column" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }}>
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
              <div className="rc-pill ok"><Icons.check size={10} />Generated by 3 agents · 1.6s</div>
              <div className="rc-pill violet"><Icons.sparkle size={10} />Custom scenario</div>
            </div>
            <h1 className="rc-h-1" style={{ margin: 0 }}>Simulation ready</h1>
            <div style={{ fontSize: 13.5, color: "var(--ink-2)", marginTop: 4 }}>Review the persona, scenario, and rubric. Edit anything that looks off, then start practice.</div>
          </div>
          <div style={{ display: "flex", gap: 8 }}>
            <button className="rc-btn"><Icons.bookmark size={13} /> Save as template</button>
            <button className="rc-btn"><Icons.retry size={13} /> Regenerate</button>
            <button className="rc-btn primary lg" onClick={() => router.push("/simulation/setup")}><Icons.video size={14} /> Start practice</button>
          </div>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1.15fr 1fr 1fr", gap: 16, flex: 1 }}>
          {/* Persona */}
          <div className="rc-glass-2" style={{ padding: 18, display: "flex", flexDirection: "column", gap: 14, position: "relative", overflow: "hidden" }}>
            <div style={{ position: "absolute", inset: 0, background: "radial-gradient(60% 60% at 100% 0%, rgba(139,125,251,0.18), transparent 60%)", pointerEvents: "none" }} />
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", position: "relative" }}>
              <div className="rc-label">Persona</div>
              <button style={{ fontSize: 11, color: "var(--ink-2)", background: "none", border: "none", cursor: "pointer" }}>Edit ↗</button>
            </div>
            <div style={{ display: "flex", gap: 14, alignItems: "flex-start", position: "relative" }}>
              <PersonaAvatar persona={p.avatar_preset as any} size={104} mood={p.mood as any} />
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 20, fontWeight: 700, letterSpacing: "-0.02em" }}>{p.name}</div>
                <div style={{ fontSize: 13, color: "var(--ink-2)", marginTop: 2 }}>{p.age} · {p.role}</div>
                <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginTop: 10 }}>
                  <div className="rc-pill warn">{p.mood}</div>
                  {p.traits?.slice(0, 2).map((t: string) => <div key={t} className="rc-pill">{t}</div>)}
                </div>
              </div>
            </div>
            <div style={{ position: "relative", display: "grid", gap: 9, fontSize: 12.5 }}>
              {[
                ["Goal", p.goal],
                ["Hidden red flag", p.hidden_red_flag],
                ["Behavior", p.behavior],
                ["Voice style", p.voice_style],
              ].map(([k, v], i) => (
                <div key={i} style={{ display: "grid", gridTemplateColumns: "110px 1fr", gap: 10 }}>
                  <div style={{ color: "var(--ink-3)", fontSize: 11, letterSpacing: "0.05em", textTransform: "uppercase", paddingTop: 2 }}>{k}</div>
                  <div style={{ color: k === "Hidden red flag" ? "#FCA5A5" : "var(--ink-1)", lineHeight: 1.5 }}>{v}</div>
                </div>
              ))}
            </div>
            <div style={{ position: "relative", padding: "12px 14px", borderRadius: 12, background: "rgba(0,0,0,0.3)", border: "1px solid var(--line)" }}>
              <div className="rc-label" style={{ marginBottom: 6, fontSize: 10 }}>Sample opening line</div>
              <div style={{ fontSize: 13, lineHeight: 1.5, color: "var(--ink-0)", fontStyle: "italic" }}>"{p.opening_line}"</div>
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 8 }}>
                <button
                  onClick={handlePlayVoice}
                  disabled={isPlayingVoice}
                  style={{ width: 24, height: 24, borderRadius: 99, border: "none", cursor: "pointer", background: "linear-gradient(135deg,#2DD4BF,#8B7DFB)", color: "#06241F", display: "grid", placeItems: "center", opacity: isPlayingVoice ? 0.7 : 1 }}
                >
                  {isPlayingVoice ? <Icons.pause size={10} /> : <Icons.play size={10} />}
                </button>
                <Waveform tone="teal" bars={28} height={14} dense />
                <span style={{ fontSize: 10, color: "var(--ink-3)" }} className="rc-mono">0:{String(openingLineDuration).padStart(2, "0")}</span>
              </div>
              {voiceError && <div style={{ marginTop: 8, fontSize: 11, color: "#FCA5A5" }}>{voiceError}</div>}
            </div>
          </div>

          {/* Scenario + Rubric */}
          <div style={{ display: "grid", gridTemplateRows: "1fr 1fr", gap: 16 }}>
            <div className="rc-glass" style={{ padding: 16, display: "flex", flexDirection: "column" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}>
                <div className="rc-label">Scenario</div>
                <div className="rc-pill warn">{s.difficulty}</div>
              </div>
              <div style={{ fontSize: 15, fontWeight: 600, marginBottom: 6 }}>{s.title}</div>
              <div style={{ fontSize: 12.5, color: "var(--ink-2)", lineHeight: 1.5, marginBottom: 10 }}>{s.description}</div>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, fontSize: 11.5, marginTop: "auto" }}>
                {[["YOUR ROLE", s.your_role], ["DURATION", s.duration], ["OBJECTIVE", s.objective], ["SUCCESS WHEN", s.success_condition]].map(([k, v]) => (
                  <div key={k}><div style={{ color: "var(--ink-3)", fontSize: 10, letterSpacing: "0.05em", marginBottom: 2 }}>{k}</div><div>{v}</div></div>
                ))}
              </div>
            </div>
            <div className="rc-glass" style={{ padding: 16, display: "flex", flexDirection: "column" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}>
                <div className="rc-label">Evaluation rubric</div>
                <button style={{ fontSize: 11, color: "var(--ink-2)", background: "none", border: "none", cursor: "pointer" }}>Edit ↗</button>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 7 }}>
                {r.items.map((item: any) => (
                  <div key={item.name} style={{ display: "flex", alignItems: "center", gap: 10, fontSize: 12 }}>
                    <span style={{ flex: 1, color: item.is_hot ? "#FCA5A5" : "var(--ink-1)", fontWeight: item.is_hot ? 500 : 400 }}>{item.name}</span>
                    <div style={{ width: 60, height: 4, background: "rgba(255,255,255,0.06)", borderRadius: 99, overflow: "hidden" }}>
                      <div style={{ height: "100%", width: `${item.weight * 4}%`, background: item.is_hot ? "linear-gradient(90deg,#F87171,#FBBF24)" : "linear-gradient(90deg,#2DD4BF,#8B7DFB)" }} />
                    </div>
                    <span style={{ width: 30, textAlign: "right", color: "var(--ink-3)", fontSize: 11 }} className="rc-mono">{item.weight}%</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Mode card + agent log */}
          <div style={{ display: "grid", gridTemplateRows: "auto 1fr", gap: 16 }}>
            <div className="rc-glass" style={{ padding: 16 }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}>
                <div className="rc-label">Simulation mode</div>
                <div className="rc-pill teal"><Icons.video size={10} />{resolvedMode === "voice" ? "Web voice" : resolvedMode === "phone" ? "Phone call" : resolvedMode === "text" ? "Text / chat" : "Web video"}</div>
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 10 }}>
                {[["Camera", "Required", <Icons.cam size={12} key="cam" />], ["Microphone", "Required", <Icons.mic size={12} key="mic" />], ["Transcript", "Live", <Icons.chat size={12} key="chat" />], ["Signals", "Audio + Video", <Icons.signal size={12} key="sig" />]].map(([l, v, i]) => (
                  <div key={String(l)} style={{ padding: "8px 10px", borderRadius: 8, background: "rgba(255,255,255,0.03)", border: "1px solid var(--line)", fontSize: 11.5 }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 6, color: "var(--ink-3)", fontSize: 10, marginBottom: 2 }}>{i}{l}</div>
                    <div>{v}</div>
                  </div>
                ))}
              </div>
              <div style={{ padding: "9px 11px", borderRadius: 8, fontSize: 11.5, lineHeight: 1.5, background: "rgba(45,212,191,0.06)", border: "1px solid rgba(45,212,191,0.25)", color: "var(--ink-1)" }}>
                Video signals are coaching estimates — not emotion or truth detection. You can disable any time.
              </div>
            </div>
            <div className="rc-glass" style={{ padding: 16, display: "flex", flexDirection: "column" }}>
              <div className="rc-label" style={{ marginBottom: 10 }}>Agent reasoning log</div>
              <div style={{ display: "flex", flexDirection: "column", gap: 9 }}>
                {resolvedAgentLog.map((l, i) => (
                  <div key={i} style={{ display: "flex", gap: 8, fontSize: 11.5, lineHeight: 1.4 }}>
                    <div style={{ width: 6, height: 6, borderRadius: 99, background: l.color, marginTop: 6, flexShrink: 0 }} />
                    <div>
                      <span style={{ color: l.color, fontWeight: 600, marginRight: 6 }}>{l.agent}</span>
                      <span style={{ color: "var(--ink-2)" }}>{l.message}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
